version: "3.8"
services:
  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
    networks:
      - webapp-network

  backend:
    build:
      context: ./backend
    container_name: backend_container
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - webapp-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend_container
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
